# -*- coding: utf-8 -*-
"""Day2_ Assignment_list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZA8sgBvfw3LT9s1LRpq1GkaqOhVhqd8W
"""

mylist=[1,2,3,4,"nilesh","padhiyar",2.33]

#listexample  1
mylist.append("last")  #adding string "last" to end of list
mylist

#listexample  2
mylist.insert(0,"zero index") # this will add "zero index" at zero positon of list
mylist

#listexample  3
mylist.remove("last") #this will remove "last" eleent from list
mylist

#listexample  4
a=mylist.index("nilesh") 
print ("index of nilesh is",a) # this prints index no of string"nilesh

#listexample  4
mylist.clear() # clear the whole list
mylist













