# -*- coding: utf-8 -*-
"""Day2_Assignment_dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9kbfeMVCeU9PPHidaIGTE_IgJ3KDaia
"""

dic={"name":"Nilesh", "age":25,"num":"97143730xx","prof":"Engineer"}

#dictionary example 1
dic.values() # returns values of dictionary

#dictionary example 2
dic.get("name") # return speecific  value by entering name

#dictionary example 3
dic.keys() # return names assosiated with values

#dictionary example 4
dic.pop("num") # it will remove specific element and return its value

dic

#dictionary example 5
dic.clear() $ clear whole dictionary

dic



















